---
- name: Converge
  hosts: all
  tasks:
    - name: Add docker repo
      shell: yum-config-manager \
             --add-repo \
             https://download.docker.com/linux/centos/docker-ce.repo
      tags:
        - molecule-idempotence-notest
    - name: install docker ce
      yum:
        name: "{{ item }}"
      with_items:
         - docker-ce
         - docker-ce-cli
         - containerd.io
    - name: service docker up
      service:
        name: docker
        state: started

    - name: "Include grafana_influxdb"
      include_role:
        name: "grafana_influxdb"
