---
# tasks file for grafana
- name: set ansible interpreter to python2
  set_fact:
    ansible_python_interpreter: /usr/bin/python2

- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- name: install packages requirement for docker-compose
  yum:
    name: "{{ item }}"
  with_items:
    - python-devel
    - gcc

- name: install docker-compose using pip
  pip:
    name: docker-compose

- name: setup docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: docker-compose.yml

- name: setup configuration file
  template:
    src: configuration.env.j2
    dest: configuration.env

- name: create grafana folder
  file:
    path: ./grafana
    state: directory

- name: create grafana folder
  file:
    path: ./influxdb
    state: directory

- name: Copy files to grafana folder
  template:
    src: "{{ item }}.j2"
    dest: "grafana/{{ item }}"
  with_items:
    - dashboards.yaml
    - datasource.yaml
    - default.json
    - gatling.json

- name: Copy files to influxdb folder
  template:
    src: "{{ item }}.j2"
    dest: "influxdb/{{ item }}"
  with_items:
    - entrypoint.sh
    - influxdb.conf

- name: Copy dockerfile for influxdb
  template:
    src: "{{ item }}.j2"
    dest: "influxdb/Dockerfile"
  with_items:
    - Dockerfile_influxdb

- name: Copy dockerfile for grafana
  template:
    src: "{{ item }}.j2"
    dest: "grafana/Dockerfile"
  with_items:
    - Dockerfile_grafana


- name: docker-compose up
  command: docker-compose up -d
  tags:
    - molecule-idempotence-notest
  changed_when: true
